# ---------------------------
# Purpose of script: Look at correlation of parameters of different TPC models
#
# What this script does:
# 1. Fits all TPC models to a all the curves from Chlorella TPC
# 2. Fits them with and without upper and lower limits
# 3. Saves them out
#
# Author: Dr. Daniel Padfield
#
# Date Created: 2024-05-29
#
# Copyright (c) Daniel Padfield, 2024
#
# ---------------------------
#
# Notes:
#
# ---------------------------

# if librarian is not installed, install it
if (!requireNamespace("librarian", quietly = TRUE)){
  install.packages("librarian")
}
# load packages
librarian::shelf(tidyverse, rTPC, nls.multstart)

## ---------------------------

# read in Chlorella TPC data
data("chlorella_tpc")

# fit a few models to the data

# load in data
data("chlorella_tpc")

d <- chlorella_tpc

# when scaling up our code to fit hundreds of models, its nice to have a progress bar
# edit nls_multstart to allow for a progress bar
nls_multstart_progress <- function(formula, data = parent.frame(), iter, start_lower, 
                                   start_upper, supp_errors = c("Y", "N"), convergence_count = 100, 
                                   control, modelweights, ...){
  if(!is.null(pb)){
    pb$tick()
  }
  nls_multstart(formula = formula, data = data, iter = iter, start_lower = start_lower, 
                start_upper = start_upper, supp_errors = supp_errors, convergence_count = convergence_count, 
                control = control, modelweights = modelweights, ...)
}

# start progress bar and estimate time it will take
number_of_models <- 26
number_of_curves <- length(unique(d$curve_id))

# setup progress bar
pb <- progress::progress_bar$new(total = number_of_curves*number_of_models,
                                 clear = FALSE,
                                 format ="[:bar] :percent :elapsedfull")

get_model_names() %>% length()

d_fits <- nest(d, data = c(temp, rate)) %>%
  mutate(
    hinshelwood = map(data, possibly(~nls_multstart_progress(rate~hinshelwood_1947(temp = temp, a, e, b, eh),
                                                             data = .x,
                                                             iter = c(5,5,5,5),
                                                             start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'hinshelwood_1947') * 0.25,
                                                             start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'hinshelwood_1947') * 1.75,
                                                             lower = get_lower_lims(.x$temp, .x$rate, model_name = 'hinshelwood_1947'),
                                                             upper = get_upper_lims(.x$temp, .x$rate, model_name = 'hinshelwood_1947'),
                                                             supp_errors = 'Y',
                                                             convergence_count = FALSE), NA)))

d_fits <- nest(d, data = c(temp, rate)) %>%
  mutate(beta = map(data, possibly(~nls_multstart_progress(rate~beta_2012(temp = temp, a, b, c, d, e),
                                         data = .x,
                                         iter = c(6,6,6,6,6),
                                         start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'beta_2012') * 0.25,
                                         start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'beta_2012') * 1.75,
                                         lower = get_lower_lims(.x$temp, .x$rate, model_name = 'beta_2012'),
                                         upper = get_upper_lims(.x$temp, .x$rate, model_name = 'beta_2012'),
                                         supp_errors = 'Y',
                                         convergence_count = FALSE), NA)),
         boatman = map(data, possibly(~nls_multstart_progress(rate~boatman_2017(temp = temp, rmax, tmin, tmax, a,b),
                                            data = .x,
                                            iter = c(5,5,5,5,5),
                                            start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'boatman_2017') * 0.25,
                                            start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'boatman_2017') * 1.75,
                                            lower = get_lower_lims(.x$temp, .x$rate, model_name = 'boatman_2017'),
                                            upper = get_upper_lims(.x$temp, .x$rate, model_name = 'boatman_2017'),
                                            supp_errors = 'Y',
                                            convergence_count = FALSE), NA)),
         briere2 = map(data, possibly(~nls_multstart_progress(rate~briere2_1999(temp = temp, tmin, tmax, a,b),
                                            data = .x,
                                            iter = c(4,4,4,4),
                                            start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'briere2_1999') * 0.25,
                                            start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'briere2_1999') * 1.75,
                                            lower = get_lower_lims(.x$temp, .x$rate, model_name = 'briere2_1999'),
                                            upper = get_upper_lims(.x$temp, .x$rate, model_name = 'briere2_1999'),
                                            supp_errors = 'Y',
                                            convergence_count = FALSE), NA)),
         delong = map(data, possibly(~nls_multstart_progress(rate~delong_2017(temp = temp, c, eb, ef, tm, ehc),
                                           data = .x,
                                           iter = c(6,6,6,6,6),
                                           start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'delong_2017') * 0.25,
                                           start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'delong_2017') * 1.75,
                                           lower = get_lower_lims(.x$temp, .x$rate, model_name = 'delong_2017'),
                                           upper = get_upper_lims(.x$temp, .x$rate, model_name = 'delong_2017'),
                                           supp_errors = 'Y',
                                           convergence_count = FALSE), NA)),
         deutsch = map(data, possibly(~nls_multstart_progress(rate~deutsch_2008(temp = temp, rmax, topt, ctmax, a),
                                            data = .x,
                                            iter = c(4,4,4,4),
                                            start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'deutsch_2008') * 0.25,
                                            start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'deutsch_2008') * 1.75,
                                            lower = get_lower_lims(.x$temp, .x$rate, model_name = 'deutsch_2008'),
                                            upper = get_upper_lims(.x$temp, .x$rate, model_name = 'deutsch_2008'),
                                            supp_errors = 'Y',
                                            convergence_count = FALSE), NA)),
         flinn = map(data, possibly(~nls_multstart_progress(rate~flinn_1991(temp = temp, a, b, c),
                                          data = .x,
                                          iter = c(5,5,5),
                                          start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'flinn_1991') * 0.25,
                                          start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'flinn_1991') * 1.75,
                                          lower = get_lower_lims(.x$temp, .x$rate, model_name = 'flinn_1991'),
                                          upper = get_upper_lims(.x$temp, .x$rate, model_name = 'flinn_1991'),
                                          supp_errors = 'Y',
                                          convergence_count = FALSE), NA)),
         gaussian = map(data, possibly(~nls_multstart_progress(rate~gaussian_1987(temp = temp, rmax, topt, a),
                                             data = .x,
                                             iter = c(4,4,4),
                                             start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'gaussian_1987') * 0.25,
                                             start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'gaussian_1987') * 1.75,
                                             lower = get_lower_lims(.x$temp, .x$rate, model_name = 'gaussian_1987'),
                                             upper = get_upper_lims(.x$temp, .x$rate, model_name = 'gaussian_1987'),
                                             supp_errors = 'Y',
                                             convergence_count = FALSE), NA)),
         hinshelwood = map(data, possibly(~nls_multstart_progress(rate~hinshelwood_1947(temp = temp, a, e, b, eh),
                                                data = .x,
                                                iter = c(5,5,5,5),
                                                start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'hinshelwood_1947') * 0.25,
                                                start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'hinshelwood_1947') * 1.75,
                                                lower = get_lower_lims(.x$temp, .x$rate, model_name = 'hinshelwood_1947'),
                                                upper = get_upper_lims(.x$temp, .x$rate, model_name = 'hinshelwood_1947'),
                                                supp_errors = 'Y',
                                                convergence_count = FALSE), NA)),
         joehnk = map(data, possibly(~nls_multstart_progress(rate~joehnk_2008(temp = temp, rmax, topt, a, b, c),
                                           data = .x,
                                           iter = c(4,4,4,4, 4),
                                           start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'joehnk_2008') * 0.25,
                                           start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'joehnk_2008') * 1.75,
                                           lower = get_lower_lims(.x$temp, .x$rate, model_name = 'joehnk_2008'),
                                           upper = get_upper_lims(.x$temp, .x$rate, model_name = 'joehnk_2008'),
                                           supp_errors = 'Y',
                                           convergence_count = FALSE), NA)),
         johnson_lewin = map(data, possibly(~nls_multstart_progress(rate~ johnsonlewin_1946(temp = temp, r0, e, eh, topt),
                                                                   data = .x,
                                                                   iter = c(4,4,4,4),
                                                                   start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'johnsonlewin_1946') * 0.25,
                                                                   start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'johnsonlewin_1946') * 1.75,
                                                                   lower = get_lower_lims(.x$temp, .x$rate, model_name = 'johnsonlewin_1946'),
                                                                   upper = get_upper_lims(.x$temp, .x$rate, model_name = 'johnsonlewin_1946'),
                                                                   supp_errors = 'Y',
                                                                   convergence_count = FALSE), NA)),
         kamykowski = map(data, possibly(~nls_multstart_progress(rate~kamykowski_1985(temp = temp, tmin, tmax, a, b, c),
                                               data = .x,
                                               iter = c(4,4,4,4,4),
                                               start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'kamykowski_1985') * 0.25,
                                               start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'kamykowski_1985') * 1.75,
                                               lower = get_lower_lims(.x$temp, .x$rate, model_name = 'kamykowski_1985'),
                                               upper = get_upper_lims(.x$temp, .x$rate, model_name = 'kamykowski_1985'),
                                               supp_errors = 'Y',
                                               convergence_count = FALSE), NA)),
         lactin2 = map(data, possibly(~nls_multstart_progress(rate~lactin2_1995(temp = temp, a, b, tmax, delta_t),
                                            data = .x,
                                            iter = c(5,5,5,5),
                                            start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'lactin2_1995') * 0.25,
                                            start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'lactin2_1995') * 1.75,
                                            lower = get_lower_lims(.x$temp, .x$rate, model_name = 'lactin2_1995'),
                                            upper = get_upper_lims(.x$temp, .x$rate, model_name = 'lactin2_1995'),
                                            supp_errors = 'Y',
                                            convergence_count = FALSE), NA)),
         lrf = map(data, possibly(~nls_multstart_progress(rate~lrf_1991(temp = temp, rmax, topt, tmin, tmax),
                                        data = .x,
                                        iter = c(3,3,3,3),
                                        start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'lrf_1991') * 0.25,
                                        start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'lrf_1991') * 1.75,
                                        lower = get_lower_lims(.x$temp, .x$rate, model_name = 'lrf_1991'),
                                        upper = get_upper_lims(.x$temp, .x$rate, model_name = 'lrf_1991'),
                                        supp_errors = 'Y',
                                        convergence_count = FALSE), NA)),
         modifiedgaussian = map(data, possibly(~nls_multstart_progress(rate~modifiedgaussian_2006(temp = temp, rmax, topt, a, b),
                                                     data = .x,
                                                     iter = c(4,4,4,4),
                                                     start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'modifiedgaussian_2006') * 0.25,
                                                     start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'modifiedgaussian_2006') * 1.75,
                                                     lower = get_lower_lims(.x$temp, .x$rate, model_name = 'modifiedgaussian_2006'),
                                                     upper = get_upper_lims(.x$temp, .x$rate, model_name = 'modifiedgaussian_2006'),
                                                     supp_errors = 'Y',
                                                     convergence_count = FALSE), NA)),
         oneill = map(data, possibly(~nls_multstart_progress(rate~oneill_1972(temp = temp, rmax, ctmax, topt, q10),
                                           data = .x,
                                           iter = c(4,4,4,4),
                                           start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'oneill_1972') * 0.25,
                                           start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'oneill_1972') * 1.75,
                                           lower = get_lower_lims(.x$temp, .x$rate, model_name = 'oneill_1972'),
                                           upper = get_upper_lims(.x$temp, .x$rate, model_name = 'oneill_1972'),
                                           supp_errors = 'Y',
                                           convergence_count = FALSE), NA)),
         pawar = map(data, possibly(~nls_multstart_progress(rate~pawar_2018(temp = temp, r_tref, e, eh, topt, tref = 15),
                                          data = .x,
                                          iter = c(4,4,4,4),
                                          start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'pawar_2018') * 0.25,
                                          start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'pawar_2018') * 1.75,
                                          lower = get_lower_lims(.x$temp, .x$rate, model_name = 'pawar_2018'),
                                          upper = get_upper_lims(.x$temp, .x$rate, model_name = 'pawar_2018'),
                                          supp_errors = 'Y',
                                          convergence_count = FALSE), NA)),
         quadratic = map(data, possibly(~nls_multstart_progress(rate~quadratic_2008(temp = temp, a, b, c),
                                              data = .x,
                                              iter = c(4,4,4),
                                              start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'quadratic_2008') * 0.25,
                                              start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'quadratic_2008') * 1.75,
                                              lower = get_lower_lims(.x$temp, .x$rate, model_name = 'quadratic_2008'),
                                              upper = get_upper_lims(.x$temp, .x$rate, model_name = 'quadratic_2008'),
                                              supp_errors = 'Y',
                                              convergence_count = FALSE), NA)),
         ratkowsky = map(data, possibly(~nls_multstart_progress(rate~ratkowsky_1983(temp = temp, tmin, tmax, a, b),
                                              data = .x,
                                              iter = c(4,4,4,4),
                                              start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'ratkowsky_1983') * 0.25,
                                              start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'ratkowsky_1983') * 1.75,
                                              lower = get_lower_lims(.x$temp, .x$rate, model_name = 'ratkowsky_1983'),
                                              upper = get_upper_lims(.x$temp, .x$rate, model_name = 'ratkowsky_1983'),
                                              supp_errors = 'Y',
                                              convergence_count = FALSE), NA)),
         rezende = map(data, possibly(~nls_multstart_progress(rate~rezende_2019(temp = temp, q10, a,b,c),
                                            data = .x,
                                            iter = c(4,4,4,4),
                                            start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'rezende_2019') * 0.25,
                                            start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'rezende_2019') * 1.75,
                                            lower = get_lower_lims(.x$temp, .x$rate, model_name = 'rezende_2019'),
                                            upper = get_upper_lims(.x$temp, .x$rate, model_name = 'rezende_2019'),
                                            supp_errors = 'Y',
                                            convergence_count = FALSE), NA)),
         sharpeschoolfull = map(data, possibly(~nls_multstart_progress(rate~sharpeschoolfull_1981(temp = temp, r_tref,e,el,tl,eh,th, tref = 15),
                                                     data = .x,
                                                     iter = c(4,4,4,4,4,4),
                                                     start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'sharpeschoolfull_1981') * 0.25,
                                                     start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'sharpeschoolfull_1981') * 1.75,
                                                     lower = get_lower_lims(.x$temp, .x$rate, model_name = 'sharpeschoolfull_1981'),
                                                     upper = get_upper_lims(.x$temp, .x$rate, model_name = 'sharpeschoolfull_1981'),
                                                     supp_errors = 'Y',
                                                     convergence_count = FALSE), NA)),
         sharpeschoolhigh = map(data, possibly(~nls_multstart_progress(rate~sharpeschoolhigh_1981(temp = temp, r_tref,e,eh,th, tref = 15),
                                                     data = .x,
                                                     iter = c(4,4,4,4),
                                                     start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'sharpeschoolhigh_1981') * 0.25,
                                                     start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'sharpeschoolhigh_1981') * 1.75,
                                                     lower = get_lower_lims(.x$temp, .x$rate, model_name = 'sharpeschoolhigh_1981'),
                                                     upper = get_upper_lims(.x$temp, .x$rate, model_name = 'sharpeschoolhigh_1981'),
                                                     supp_errors = 'Y',
                                                     convergence_count = FALSE), NA)),
         sharpeschoollow = map(data, possibly(~nls_multstart_progress(rate~sharpeschoollow_1981(temp = temp, r_tref,e,el,tl, tref = 15),
                                                    data = .x,
                                                    iter = c(4,4,4,4),
                                                    start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'sharpeschoollow_1981') * 0.25,
                                                    start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'sharpeschoollow_1981') * 1.75,
                                                    lower = get_lower_lims(.x$temp, .x$rate, model_name = 'sharpeschoollow_1981'),
                                                    upper = get_upper_lims(.x$temp, .x$rate, model_name = 'sharpeschoollow_1981'),
                                                    supp_errors = 'Y',
                                                    convergence_count = FALSE), NA)),
         spain = map(data, possibly(~nls_multstart_progress(rate~spain_1982(temp = temp, a,b,c,r0),
                                          data = .x,
                                          iter = c(4,4,4,4),
                                          start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'spain_1982') * 0.25,
                                          start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'spain_1982') * 1.75,
                                          lower = get_lower_lims(.x$temp, .x$rate, model_name = 'spain_1982'),
                                          upper = get_upper_lims(.x$temp, .x$rate, model_name = 'spain_1982'),
                                          supp_errors = 'Y',
                                          convergence_count = FALSE), NA)),
         thomas1 = map(data, possibly(~nls_multstart_progress(rate~thomas_2012(temp = temp, a,b,c,tref),
                                            data = .x,
                                            iter = c(4,4,4,4),
                                            start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'thomas_2012') * 0.25,
                                            start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'thomas_2012') * 1.75,
                                            lower = get_lower_lims(.x$temp, .x$rate, model_name = 'thomas_2012'),
                                            upper = get_upper_lims(.x$temp, .x$rate, model_name = 'thomas_2012'),
                                            supp_errors = 'Y',
                                            convergence_count = FALSE), NA)),
         thomas2 = map(data, possibly(~nls_multstart_progress(rate~thomas_2017(temp = temp, a,b,c,d,e),
                                            data = .x,
                                            iter = c(3,3,3,3,3),
                                            start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'thomas_2017') * 0.25,
                                            start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'thomas_2017') * 1.75,
                                            lower = get_lower_lims(.x$temp, .x$rate, model_name = 'thomas_2017'),
                                            upper = get_upper_lims(.x$temp, .x$rate, model_name = 'thomas_2017'),
                                            supp_errors = 'Y',
                                            convergence_count = FALSE), NA)),
         weibull = map(data, possibly(~nls_multstart_progress(rate~weibull_1995(temp = temp, a,topt,b,c),
                                            data = .x,
                                            iter = c(4,4,4,4),
                                            start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'weibull_1995') * 0.25,
                                            start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'weibull_1995') * 1.75,
                                            lower = get_lower_lims(.x$temp, .x$rate, model_name = 'weibull_1995'),
                                            upper = get_upper_lims(.x$temp, .x$rate, model_name = 'weibull_1995'),
                                            supp_errors = 'Y',
                                            convergence_count = FALSE), NA)))

# 24:19
# save out all model fits
saveRDS(d_fits, 'data/chlorella_allTPCfits_withlimits.rds')

# setup progress bar
pb <- progress::progress_bar$new(total = number_of_curves*number_of_models,
                                 clear = FALSE,
                                 format ="[:bar] :percent :elapsedfull")

# fit with no limits
d_fits2 <- nest(d, data = c(temp, rate)) %>%
  mutate(beta = map(data, possibly(~nls_multstart_progress(rate~beta_2012(temp = temp, a, b, c, d, e),
                                                  data = .x,
                                                  iter = c(6,6,6,6,6),
                                                  start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'beta_2012') * 0.25,
                                                  start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'beta_2012') * 1.75,
                                                  supp_errors = 'Y',
                                                  convergence_count = FALSE), NA)),
         boatman = map(data, possibly(~nls_multstart_progress(rate~boatman_2017(temp = temp, rmax, tmin, tmax, a,b),
                                                     data = .x,
                                                     iter = c(5,5,5,5,5),
                                                     start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'boatman_2017') * 0.25,
                                                     start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'boatman_2017') * 1.75,
                                                     supp_errors = 'Y',
                                                     convergence_count = FALSE), NA)),
         briere2 = map(data, possibly(~nls_multstart_progress(rate~briere2_1999(temp = temp, tmin, tmax, a,b),
                                                     data = .x,
                                                     iter = c(4,4,4,4),
                                                     start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'briere2_1999') * 0.25,
                                                     start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'briere2_1999') * 1.75,
                                                     supp_errors = 'Y',
                                                     convergence_count = FALSE), NA)),
         delong = map(data, possibly(~nls_multstart_progress(rate~delong_2017(temp = temp, c, eb, ef, tm, ehc),
                                                    data = .x,
                                                    iter = c(6,6,6,6,6),
                                                    start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'delong_2017') * 0.25,
                                                    start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'delong_2017') * 1.75,
                                                    supp_errors = 'Y',
                                                    convergence_count = FALSE), NA)),
         deutsch = map(data, possibly(~nls_multstart_progress(rate~deutsch_2008(temp = temp, rmax, topt, ctmax, a),
                                                     data = .x,
                                                     iter = c(4,4,4,4),
                                                     start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'deutsch_2008') * 0.25,
                                                     start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'deutsch_2008') * 1.75,
                                                     supp_errors = 'Y',
                                                     convergence_count = FALSE), NA)),
         flinn = map(data, possibly(~nls_multstart_progress(rate~flinn_1991(temp = temp, a, b, c),
                                                   data = .x,
                                                   iter = c(5,5,5),
                                                   start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'flinn_1991') * 0.25,
                                                   start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'flinn_1991') * 1.75,
                                                   supp_errors = 'Y',
                                                   convergence_count = FALSE), NA)),
         gaussian = map(data, possibly(~nls_multstart_progress(rate~gaussian_1987(temp = temp, rmax, topt, a),
                                                      data = .x,
                                                      iter = c(4,4,4),
                                                      start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'gaussian_1987') * 0.25,
                                                      start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'gaussian_1987') * 1.75,
                                                      supp_errors = 'Y',
                                                      convergence_count = FALSE), NA)),
         hinshelwood = map(data, possibly(~nls_multstart_progress(rate~hinshelwood_1947(temp = temp, a, e, b, eh),
                                                         data = .x,
                                                         iter = c(5,5,5,5),
                                                         start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'hinshelwood_1947') * 0.25,
                                                         start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'hinshelwood_1947') * 1.75,
                                                         supp_errors = 'Y',
                                                         convergence_count = FALSE), NA)),
         joehnk = map(data, possibly(~nls_multstart_progress(rate~joehnk_2008(temp = temp, rmax, topt, a, b, c),
                                                    data = .x,
                                                    iter = c(4,4,4,4, 4),
                                                    start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'joehnk_2008') * 0.25,
                                                    start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'joehnk_2008') * 1.75,
                                                    supp_errors = 'Y',
                                                    convergence_count = FALSE), NA)),
         johnson_lewin = map(data, possibly(~nls_multstart_progress(rate~ johnsonlewin_1946(temp = temp, r0, e, eh, topt),
                                                                            data = .x,
                                                                            iter = c(4,4,4,4),
                                                                            start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'johnsonlewin_1946') * 0.25,
                                                                            start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'johnsonlewin_1946') * 1.75,
                                                                            supp_errors = 'Y',
                                                                            convergence_count = FALSE), NA)),
         kamykowski = map(data, possibly(~nls_multstart_progress(rate~kamykowski_1985(temp = temp, tmin, tmax, a, b, c),
                                                        data = .x,
                                                        iter = c(4,4,4,4,4),
                                                        start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'kamykowski_1985') * 0.25,
                                                        start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'kamykowski_1985') * 1.75,
                                                        supp_errors = 'Y',
                                                        convergence_count = FALSE), NA)),
         lactin2 = map(data, possibly(~nls_multstart_progress(rate~lactin2_1995(temp = temp, a, b, tmax, delta_t),
                                                     data = .x,
                                                     iter = c(5,5,5,5),
                                                     start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'lactin2_1995') * 0.25,
                                                     start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'lactin2_1995') * 1.75,
                                                     supp_errors = 'Y',
                                                     convergence_count = FALSE), NA)),
         lrf = map(data, possibly(~nls_multstart_progress(rate~lrf_1991(temp = temp, rmax, topt, tmin, tmax),
                                                 data = .x,
                                                 iter = c(3,3,3,3),
                                                 start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'lrf_1991') * 0.25,
                                                 start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'lrf_1991') * 1.75,
                                                 supp_errors = 'Y',
                                                 convergence_count = FALSE), NA)),
         modifiedgaussian = map(data, possibly(~nls_multstart_progress(rate~modifiedgaussian_2006(temp = temp, rmax, topt, a, b),
                                                              data = .x,
                                                              iter = c(4,4,4,4),
                                                              start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'modifiedgaussian_2006') * 0.25,
                                                              start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'modifiedgaussian_2006') * 1.75,
                                                              supp_errors = 'Y',
                                                              convergence_count = FALSE), NA)),
         oneill = map(data, possibly(~nls_multstart_progress(rate~oneill_1972(temp = temp, rmax, ctmax, topt, q10),
                                                    data = .x,
                                                    iter = c(4,4,4,4),
                                                    start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'oneill_1972') * 0.25,
                                                    start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'oneill_1972') * 1.75,
                                                    supp_errors = 'Y',
                                                    convergence_count = FALSE), NA)),
         pawar = map(data, possibly(~nls_multstart_progress(rate~pawar_2018(temp = temp, r_tref, e, eh, topt, tref = 15),
                                                   data = .x,
                                                   iter = c(4,4,4,4),
                                                   start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'pawar_2018') * 0.25,
                                                   start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'pawar_2018') * 1.75,
                                                   supp_errors = 'Y',
                                                   convergence_count = FALSE), NA)),
         quadratic = map(data, possibly(~nls_multstart_progress(rate~quadratic_2008(temp = temp, a, b, c),
                                                       data = .x,
                                                       iter = c(4,4,4),
                                                       start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'quadratic_2008') * 0.25,
                                                       start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'quadratic_2008') * 1.75,
                                                       supp_errors = 'Y',
                                                       convergence_count = FALSE), NA)),
         ratkowsky = map(data, possibly(~nls_multstart_progress(rate~ratkowsky_1983(temp = temp, tmin, tmax, a, b),
                                                       data = .x,
                                                       iter = c(4,4,4,4),
                                                       start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'ratkowsky_1983') * 0.25,
                                                       start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'ratkowsky_1983') * 1.75,
                                                       supp_errors = 'Y',
                                                       convergence_count = FALSE), NA)),
         rezende = map(data, possibly(~nls_multstart_progress(rate~rezende_2019(temp = temp, q10, a,b,c),
                                                     data = .x,
                                                     iter = c(4,4,4,4),
                                                     start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'rezende_2019') * 0.25,
                                                     start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'rezende_2019') * 1.75,
                                                     supp_errors = 'Y',
                                                     convergence_count = FALSE), NA)),
         sharpeschoolfull = map(data, possibly(~nls_multstart_progress(rate~sharpeschoolfull_1981(temp = temp, r_tref,e,el,tl,eh,th, tref = 15),
                                                              data = .x,
                                                              iter = c(4,4,4,4,4,4),
                                                              start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'sharpeschoolfull_1981') * 0.25,
                                                              start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'sharpeschoolfull_1981') * 1.75,
                                                              supp_errors = 'Y',
                                                              convergence_count = FALSE), NA)),
         sharpeschoolhigh = map(data, possibly(~nls_multstart_progress(rate~sharpeschoolhigh_1981(temp = temp, r_tref,e,eh,th, tref = 15),
                                                              data = .x,
                                                              iter = c(4,4,4,4),
                                                              start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'sharpeschoolhigh_1981') * 0.25,
                                                              start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'sharpeschoolhigh_1981') * 1.75,
                                                              supp_errors = 'Y',
                                                              convergence_count = FALSE), NA)),
         sharpeschoollow = map(data, possibly(~nls_multstart_progress(rate~sharpeschoollow_1981(temp = temp, r_tref,e,el,tl, tref = 15),
                                                             data = .x,
                                                             iter = c(4,4,4,4),
                                                             start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'sharpeschoollow_1981') * 0.25,
                                                             start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'sharpeschoollow_1981') * 1.75,
                                                             supp_errors = 'Y',
                                                             convergence_count = FALSE), NA)),
         spain = map(data, possibly(~nls_multstart_progress(rate~spain_1982(temp = temp, a,b,c,r0),
                                                   data = .x,
                                                   iter = c(4,4,4,4),
                                                   start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'spain_1982') * 0.25,
                                                   start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'spain_1982') * 1.75,
                                                   supp_errors = 'Y',
                                                   convergence_count = FALSE), NA)),
         thomas1 = map(data, possibly(~nls_multstart_progress(rate~thomas_2012(temp = temp, a,b,c,tref),
                                                     data = .x,
                                                     iter = c(4,4,4,4),
                                                     start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'thomas_2012') * 0.25,
                                                     start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'thomas_2012') * 1.75,
                                                     supp_errors = 'Y',
                                                     convergence_count = FALSE), NA)),
         thomas2 = map(data, possibly(~nls_multstart_progress(rate~thomas_2017(temp = temp, a,b,c,d,e),
                                                     data = .x,
                                                     iter = c(3,3,3,3,3),
                                                     start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'thomas_2017') * 0.25,
                                                     start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'thomas_2017') * 1.75,
                                                     supp_errors = 'Y',
                                                     convergence_count = FALSE), NA)),
         weibull = map(data, possibly(~nls_multstart_progress(rate~weibull_1995(temp = temp, a,topt,b,c),
                                                     data = .x,
                                                     iter = c(4,4,4,4),
                                                     start_lower = get_start_vals(.x$temp, .x$rate, model_name = 'weibull_1995') * 0.25,
                                                     start_upper = get_start_vals(.x$temp, .x$rate, model_name = 'weibull_1995') * 1.75,
                                                     supp_errors = 'Y',
                                                     convergence_count = FALSE), NA)))

# save out all model fits
saveRDS(d_fits2, 'data/chlorella_allTPCfits_nolimits.rds')